# Generated by Django 3.0 on 2019-09-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Majmu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page', models.IntegerField()),
                ('image', models.CharField(max_length=2083)),
            ],
        ),
    ]
