# Generated by Django 3.0 on 2019-09-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majmu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majmu',
            name='image',
        ),
    ]
