# Generated by Django 3.0 on 2019-09-25 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majmu', '0004_auto_20190925_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='majmu',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
