# Generated by Django 3.0 on 2019-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majmu', '0005_majmu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majmu',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
